### ISSUE TITLE
Add option to exclude `hidden` commands, options and groups

### ISSUE THREAD

**Issue by jan-golda** [DataDog/mkdocs-click#51]
Hi! The `mkdocs-click` works great for me, thanks :bow: 

But I have encountered one problem: `mkdocs-click` does not take into account the Click's `hidden` flag. I have some groups of commands that are hidden from the `--help` page and in turn, I would like to also exclude them from the docs.

Click supports `hidden` both in `Command` and `Option`. We could add a flag to `mkdocs-click` that would filter them out during docs generation.

I could contribute such a feature, but first I would like to discuss that with you.

**Comment by ofek** [comment]
We would gladly accept such a contribution!

**Comment by ofek** [comment]
In fact, I would make this the default behavior and add a `show_hidden` option.
